### ISSUE TITLE
feat: Support for custom http headers

### ISSUE THREAD

**Issue by ivarconr** [Unleash/unleash-php-sdk#1]
First of, thanks for taking the time to put this together, awesome! 👍🏼 

It would be good to add support for custom http headers (at least I could not find a way looking briefly at the code). Starting from Unleash v4 all SDKs needs to also add a "API token" as the `Authorization` header in order to connect to the Unleash AP. It would be good if there was a way to pass custom http headers to this SDK as well. 

An example on how this is solved would be any of the other official SDKs, e.g. the [go SDK](https://docs.getunleash.io/sdks/go_sdk).

**Comment by RikudouSage** [comment]
It's possible using middleware, but it's definitely better to support it directly, I'll look into it, thanks for the info!
